# Micronaut Application Configuration
micronaut.application.name=swift-backend
micronaut.server.port=8080
micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.all.allowedOrigins[0]=*
micronaut.server.cors.configurations.all.allowedHeaders[0]=*
micronaut.server.cors.configurations.all.allowedMethods[0]=*

# Configurações de banco de dados Oracle
db.url=jdbc:oracle:thin:@localhost:1521:xe
db.username=system
db.password=oracle
db.driver=oracle.jdbc.OracleDriver
